spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: root
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
